import{S as p,i as l}from"./assets/vendor-0fc460d7.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const m={PIXABAY:{PATH:"https://pixabay.com/api/",KEY:"44444020-42ceddb875011e5970bd122af"}},f=async(t,i)=>{try{const r=new URLSearchParams({key:m.PIXABAY.KEY,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}),o=await fetch(m.PIXABAY.PATH+"?"+r.toString());if(!o.ok)throw new Error("Failed to fetch images");return o}catch(r){throw console.error("Error fetching images:",r),r}},u=t=>`
    <a href="${t.largeImageURL}" class="item">
      <img src="${t.webformatURL}" alt="" alt="${t.tags}"/>
      <div class="data">
        <p><b>Likes</b> <span>${t.likes}</span></p>
        <p><b>Views</b> <span>${t.views}</span></p>
        <p><b>Comments</b> <span>${t.comments}</span></p>
        <p><b>Downloads</b> <span>${t.downloads}</span></p>
      </div>
    </a>
  `,a=document.querySelector("form.form-search"),n=document.querySelector(".gallery"),h=new p(".gallery a",{});a&&a.addEventListener("submit",t=>{t.preventDefault();const i=a.elements.search.value;i?(n.innerHTML="",n.classList.add("is-load"),f(i).then(r=>{if(!r.ok)throw new Error(r.status);return r.json()}).then(r=>{n.classList.remove("is-load");const o=[];r.total===0?l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",class:"error",color:"red"}):(r.hits.forEach(e=>{o.push(u(e))}),n.innerHTML=o.join(""),h.refresh())}).catch(r=>{n.classList.remove("is-load"),l.error({message:`Sorry, something went wrong! ${r.message}`,position:"topRight",class:"error",color:"red"})}),a.reset()):l.error({message:"Please enter a search term",position:"topRight",class:"error",color:"red"})});
//# sourceMappingURL=commonHelpers.js.map
